server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: board-api
  datasource:
    url: jdbc:postgresql://localhost:5432/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
